In [3]:
#Bai 1
import numpy as np

arr1 = np.array([1, 2, 3, 2, 5, 1, 7, 9, 9, 4])

even_positions = arr1[1::2]
print(f"Các vị trí chẵn: {even_positions}")

arrTuple = tuple(arr1)
print(f"Tuple: {arrTuple}")

arrDict = {i: arr1[i] for i in range(len(arr1))}
print(f"Dict: {arrDict}")

arrSet = set(arr1)
print(f"Set: {arrSet}")

removed = len(arr1) - len(arrSet)
print(f"Số phần tử bị loại trùng: {removed}")


Các vị trí chẵn: [2 2 1 9 4]
Tuple: (np.int64(1), np.int64(2), np.int64(3), np.int64(2), np.int64(5), np.int64(1), np.int64(7), np.int64(9), np.int64(9), np.int64(4))
Dict: {0: np.int64(1), 1: np.int64(2), 2: np.int64(3), 3: np.int64(2), 4: np.int64(5), 5: np.int64(1), 6: np.int64(7), 7: np.int64(9), 8: np.int64(9), 9: np.int64(4)}
Set: {np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(7), np.int64(9)}
Số phần tử bị loại trùng: 3


In [4]:
#bai 2
import json

with open("data.txt", "w", encoding="utf-8") as f:
    lines = [
        "Dòng 1: Đây là dòng đầu tiên",
        "Dòng 2: Python rất thú vị",
        "Dòng 3: Học lập trình mỗi ngày",
        "Dòng 4: File handling không khó",
        "Dòng 5: Kết thúc bài tập"
    ]
    f.write("\n".join(lines))
with open("data.txt", "r", encoding="utf-8") as f:
    for line in f:
        print(line.strip())

student = {
    "name": "An",
    "age": 20,
    "scores": [8, 9, 7]
}

with open("student.json", "w", encoding="utf-8") as f:
    json.dump(student, f, ensure_ascii=False, indent=2)

with open("student.json", "r", encoding="utf-8") as f:
    data = json.load(f)
    print("JSON đọc từ file:", data)


Dòng 1: Đây là dòng đầu tiên
Dòng 2: Python rất thú vị
Dòng 3: Học lập trình mỗi ngày
Dòng 4: File handling không khó
Dòng 5: Kết thúc bài tập
JSON đọc từ file: {'name': 'An', 'age': 20, 'scores': [8, 9, 7]}


In [ ]:
#Bai 3
import numpy as np

arr = np.arange(12).reshape(3, 4)

row2 = arr[1]
print("Hàng 2:", row2)

col3 = arr[:, 2]
print("Cột 3:", col3)

sub = arr[1:3, 1:3]
print("Submatrix:", sub)

arr_float = arr.astype(np.float64)
print("Dtype mới:", arr_float.dtype)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrix: [[ 5  6]
 [ 9 10]]
Dtype mới: float64


In [6]:
#Bai. 4
import pandas as pd

names = ['An', 'Bình', 'Châu', 'Dũng', 'Hà']
ages = [20, 21, 22, 20, 23]
scores = [7.5, 8.0, 6.5, 9.0, 8.5]

s = pd.Series(scores)

df = pd.DataFrame({
    "name": names,
    "age": ages,
    "score": scores
})

print(df.info())
print(df.describe())

filtered = df[df["score"] >= 8.0]
print("Sinh viên >= 8 điểm:")
print(filtered.values.tolist())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   age     5 non-null      int64  
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes
None
            age     score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000
Sinh viên >= 8 điểm:
[['Bình', 21, 8.0], ['Dũng', 20, 9.0], ['Hà', 23, 8.5]]


In [7]:
#Bai 5
import pandas as pd

with open("students.csv", "w", encoding="utf-8") as f:
    f.write("id,name\n1,An\n2,Binh\n3,Chau\n")

with open("scores.csv", "w", encoding="utf-8") as f:
    f.write("id,score\n1,8\n2,9\n3,7\n")

students = pd.read_csv("students.csv")
scores = pd.read_csv("scores.csv")

df = students.merge(scores, on="id")

report = df.groupby(["id", "name"])["score"].agg(
    score_min="min",
    score_max="max",
    score_mean="mean"
).reset_index()

report.to_csv("report.csv", index=False)

print(report)


   id  name  score_min  score_max  score_mean
0   1    An          8          8         8.0
1   2  Binh          9          9         9.0
2   3  Chau          7          7         7.0


In [8]:
#Bai 6
import numpy as np

a = np.array([[1], [2], [3], [4]])
b = np.array([[10, 20, 30, 40, 50]])

res = a * b
print("a * b:\n", res)

sqrt_res = np.sqrt(res)
print("sqrt:\n", sqrt_res)

log_res = np.log(res)
print("log:\n", log_res)

mean_axis1 = res.mean(axis=1)
print("mean axis=1:", mean_axis1)

min_axis1 = res.min(axis=1)
max_axis1 = res.max(axis=1)
std_axis1 = res.std(axis=1)

print("min axis=1:", min_axis1)
print("max axis=1:", max_axis1)
print("std axis=1:", std_axis1)


a * b:
 [[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
sqrt:
 [[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]
log:
 [[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]
mean axis=1: [ 30.  60.  90. 120.]
min axis=1: [10 20 30 40]
max axis=1: [ 50 100 150 200]
std axis=1: [14.14213562 28.28427125 42.42640687 56.56854249]


In [9]:
#Bai 7
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["An", "Bình", "Châu", "Dũng"],
    "age": [20, np.nan, 22, 21],
    "score": [8.5, np.nan, 7.0, 9.0],
    "city": ["Hà Nội", "HCM", np.nan, "Hà Nội"]
})

missing = df.isna()
print(missing)

df["age"] = df["age"].fillna(df["age"].mean())
df["score"] = df["score"].fillna(df["score"].median())
df["city"] = df["city"].fillna("Unknown")

df["city"] = df["city"].astype("category")

def level(x):
    if x >= 8:
        return "Good"
    elif x >= 7:
        return "Average"
    return "Bad"

df["score_level"] = df["score"].apply(level)

age_mean = df["age"].mean()
age_std = df["age"].std()
df["age_normalized"] = (df["age"] - age_mean) / age_std

print(df)


    name    age  score   city
0  False  False  False  False
1  False   True   True  False
2  False  False  False   True
3  False  False  False  False
   name   age  score     city score_level  age_normalized
0    An  20.0    8.5   Hà Nội        Good       -1.224745
1  Bình  21.0    8.5      HCM        Good        0.000000
2  Châu  22.0    7.0  Unknown     Average        1.224745
3  Dũng  21.0    9.0   Hà Nội        Good        0.000000


In [1]:
#Bai 8
from pathlib import Path
from datetime import datetime
import json
import pandas as pd

log_dir = Path("logs")
files = list(log_dir.glob("log_*.json"))

records = []

for f in files:
    date_str = f.stem.split("_")[1]
    day = datetime.strptime(date_str, "%Y-%m-%d").date()
    with open(f, "r", encoding="utf-8") as file:
        data = json.load(file)
        data["date"] = day
        records.append(data)

df = pd.DataFrame(records)

report = df.groupby("date")["duration"].sum().reset_index()

report.to_csv("daily_report.csv", index=False)

print(report)


         date  duration
0  2024-01-01         5
1  2024-01-02         3
