In [8]:
#Bai 1
import numpy as np

arr1 = np.arange(1,11)
print(f"Shape1 = {np.shape(arr1)}")
print(f"Dtype1 = {(arr1.astype(float)).dtype}")

arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"Shape 2 = {np.shape(arr2)}")
print(f"Dtype2 = {arr2.dtype}")


Shape1 = (10,)
Dtype1 = float64
Shape 2 = (3, 3)
Dtype2 = int64


In [14]:
#Bai 2
import numpy as np
arr1 = np.arange(1, 11)
first_elem = arr1[0]
last_elem = arr1[-1]

middle_elem = arr1[(len(arr1)-1)//2]

sliced_arr = arr1[2:5]

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

row2 = arr2[1]

col3 = arr2[:, 2]

print("\nfirst_elem =", first_elem)
print("last_elem =", last_elem)
print("middle_elem =", middle_elem)
print("sliced_arr =", sliced_arr)
print("row2 =", row2)
print("col3 =", col3)



first_elem = 1
last_elem = 10
middle_elem = 5
sliced_arr = [3 4 5]
row2 = [4 5 6]
col3 = [3 6 9]


In [18]:
#Bai 3
import numpy as np
arr = np.array([[88, 35, 62],
                [11, 98, 34],
                [64, 24, 48]])

min_val = np.min(arr)
max_val = np.max(arr)
sum_val = np.sum(arr)
mean_val = np.mean(arr)
std_val = np.std(arr)
sum_col = np.sum(arr, axis=0)
mean_col = np.mean(arr, axis=0)
sum_row = np.sum(arr, axis=1)
mean_row = np.mean(arr, axis=1)

print("\nMin:", min_val)
print("Max:", max_val)
print("Sum:", sum_val)
print("Mean:", mean_val)
print("STD:", std_val)
print("\nSumOfColumn:", sum_col)
print("MeanOfColumn:", mean_col)
print("\nSumOfRow:", sum_row)
print("MeanOfRow:", mean_row)



Min: 11
Max: 98
Sum: 464
Mean: 51.55555555555556
STD: 27.38252123409754

SumOfColumn: [163 157 144]
MeanOfColumn: [54.33333333 52.33333333 48.        ]

SumOfRow: [185 143 136]
MeanOfRow: [61.66666667 47.66666667 45.33333333]


In [19]:
#Bai 4
import numpy as np

A = np.array([[5, 6, 8],
              [7, 2, 4],
              [1, 6, 3]])

B = np.array([10, 20, 30])

print(A)
print("\n", B)

add_result = A + B
sub_result = A - B

print("\nKết quả phép cộng A + B:")
print(add_result)

print("\nKết quả phép trừ A - B:")
print(sub_result)


[[5 6 8]
 [7 2 4]
 [1 6 3]]

 [10 20 30]

Kết quả phép cộng A + B:
[[15 26 38]
 [17 22 34]
 [11 26 33]]

Kết quả phép trừ A - B:
[[ -5 -14 -22]
 [ -3 -18 -26]
 [ -9 -14 -27]]


In [20]:
#Bai 5
import numpy as np
import time

arr = np.random.randint(1, 21, size=10)
print("Mảng ban đầu:", arr)

squared = arr ** 2    
sqrt_arr = np.sqrt(arr)  

print("\nBình phương (vectorized):", squared)
print("Căn bậc hai (vectorized):", sqrt_arr)

add_result = np.add(arr, 5)        
mul_result = np.multiply(arr, 3)  
sqrt_ufunc = np.sqrt(arr)        

print("\nKết quả dùng ufunc:")
print("np.add(arr, 5)       :", add_result)
print("np.multiply(arr, 3)  :", mul_result)
print("np.sqrt(arr)         :", sqrt_ufunc)

arr2D = np.random.randint(1, 100, size=(1000, 1000))

start_vec = time.time()
res_vec = arr2D * 2 + 5
end_vec = time.time()

start_loop = time.time()
res_loop = np.zeros_like(arr2D)
for i in range(arr2D.shape[0]):
    for j in range(arr2D.shape[1]):
        res_loop[i, j] = arr2D[i, j] * 2 + 5
end_loop = time.time()

print("\n--- So sánh tốc độ ---")
print("Vectorized time:", end_vec - start_vec, "seconds")
print("Loop time      :", end_loop - start_loop, "seconds")


Mảng ban đầu: [ 8 17 18  5  3 14  5  3 15  4]

Bình phương (vectorized): [ 64 289 324  25   9 196  25   9 225  16]
Căn bậc hai (vectorized): [2.82842712 4.12310563 4.24264069 2.23606798 1.73205081 3.74165739
 2.23606798 1.73205081 3.87298335 2.        ]

Kết quả dùng ufunc:
np.add(arr, 5)       : [13 22 23 10  8 19 10  8 20  9]
np.multiply(arr, 3)  : [24 51 54 15  9 42 15  9 45 12]
np.sqrt(arr)         : [2.82842712 4.12310563 4.24264069 2.23606798 1.73205081 3.74165739
 2.23606798 1.73205081 3.87298335 2.        ]

--- So sánh tốc độ ---
Vectorized time: 0.015194892883300781 seconds
Loop time      : 0.5800447463989258 seconds


In [23]:
#Bai 6
import numpy as np

arr = np.array([
    [3, 7, 4, 5],
    [3, 5, 2, 4],
    [6, 3, 9, 7],
    [4, 8, 3, 5]
])

sum_col = np.sum(arr, axis=0)
mean_col = np.mean(arr, axis=0)
std_col = np.std(arr, axis=0)
sum_row = np.sum(arr, axis=1)
mean_row = np.mean(arr, axis=1)
std_row = np.std(arr, axis=1)

print("\nTổng theo cột (axis=0):", sum_col)
print("Trung bình theo cột (axis=0):", mean_col)
print("Độ lệch chuẩn theo cột (axis=0):", std_col)

print("\nTổng theo hàng (axis=1):", sum_row)
print("Trung bình theo hàng (axis=1):", mean_row)
print("Độ lệch chuẩn theo hàng (axis=1):", std_row)



Tổng theo cột (axis=0): [16 23 18 21]
Trung bình theo cột (axis=0): [4.   5.75 4.5  5.25]
Độ lệch chuẩn theo cột (axis=0): [1.22474487 1.92028644 2.6925824  1.08972474]

Tổng theo hàng (axis=1): [19 14 25 20]
Trung bình theo hàng (axis=1): [4.75 3.5  6.25 5.  ]
Độ lệch chuẩn theo hàng (axis=1): [1.47901995 1.11803399 2.16506351 1.87082869]


In [24]:
#Bai 7
import numpy as np
import time
A = np.array([
    [ 8, 12, 14,  6,  4],
    [18, 13,  2,  2, 12],
    [ 6, 18,  5, 10, 10],
    [ 9,  2,  4, 12, 12],
    [ 2,  3,  2, 17,  3]
])
B = np.array([10, 20, 30, 40, 50])
add_broad = A + B
sub_broad = A - B

print("\nKết quả cộng (broadcasting):")
print(add_broad)

print("\nKết quả trừ (broadcasting):")
print(sub_broad)

sqrt_res = np.sqrt(A)
print("\nKết quả căn bậc hai (ufunc):")
print(sqrt_res)

add5_res = np.add(A, 5)
print("\nKết quả cộng 5 vào mảng (ufunc):")
print(add5_res)

start_loop = time.time()
result_loop = np.zeros_like(A)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        result_loop[i, j] = A[i, j] + B[j]   

end_loop = time.time()
loop_time = end_loop - start_loop

print("\nThời gian thực thi vòng lặp thủ công:", round(loop_time, 6), "giây")



Kết quả cộng (broadcasting):
[[18 32 44 46 54]
 [28 33 32 42 62]
 [16 38 35 50 60]
 [19 22 34 52 62]
 [12 23 32 57 53]]

Kết quả trừ (broadcasting):
[[ -2  -8 -16 -34 -46]
 [  8  -7 -28 -38 -38]
 [ -4  -2 -25 -30 -40]
 [ -1 -18 -26 -28 -38]
 [ -8 -17 -28 -23 -47]]

Kết quả căn bậc hai (ufunc):
[[2.82842712 3.46410162 3.74165739 2.44948974 2.        ]
 [4.24264069 3.60555128 1.41421356 1.41421356 3.46410162]
 [2.44948974 4.24264069 2.23606798 3.16227766 3.16227766]
 [3.         1.41421356 2.         3.46410162 3.46410162]
 [1.41421356 1.73205081 1.41421356 4.12310563 1.73205081]]

Kết quả cộng 5 vào mảng (ufunc):
[[13 17 19 11  9]
 [23 18  7  7 17]
 [11 23 10 15 15]
 [14  7  9 17 17]
 [ 7  8  7 22  8]]

Thời gian thực thi vòng lặp thủ công: 0.000237 giây


In [25]:
#Bai 8
import numpy as np

A = np.array([
    [6, 9, 7],
    [2, 1, 5],
    [7, 8, 3]
])
inv_A = np.linalg.inv(A)
print("\nMa trận nghịch đảo:\n")
print(inv_A)

eigen_values, eigen_vectors = np.linalg.eig(A)

print("\nGiá trị riêng của ma trận:", eigen_values)

print("\nVéc tơ riêng của ma trận:\n")
print(eigen_vectors)



Ma trận nghịch đảo:

[[-0.3627451   0.28431373  0.37254902]
 [ 0.28431373 -0.30392157 -0.15686275]
 [ 0.08823529  0.14705882 -0.11764706]]

Giá trị riêng của ma trận: [15.56193425 -1.69500073 -3.86693352]

Véc tơ riêng của ma trận:

[[-0.73366783 -0.72778239  0.22947148]
 [-0.30862775  0.68155654 -0.7417394 ]
 [-0.60537626 -0.07624612  0.63021068]]
